import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    width:'100%',
    position: 'relative',
    display: 'flex',
    flex: 1,
    alignItems: 'center',
    justifyContent: 'start',
    flexDirection: "column",
  },
  logoContainer: {
    width: '100%',
    height: '18%',
    alignItems: 'center',
    justifyContent: 'center',
    borderBlockColor: '#128912',
    borderBottomWidth: 2,
    backgroundColor:'white'
  },
  productSearch: {
    width: '100%',
    height: '11%',
    alignItems: 'center',
    justifyContent: 'space-around',
    borderBlockColor: '#128912',
    borderBottomWidth: 2,
    flexDirection: 'row'
  },
  displayContainer: {
    position: 'relative',
    width: '100%',
    height: '66%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  infoContainer: {
    position: 'relative',
    width: '100%',
    height: '13%',
    alignItems: 'center',
    justifyContent: 'space-around',
    flexDirection:'row',
  },
  backBar: {
    position: 'relative',
    width: '100%',
    height: '10%',
    alignItems: 'center',
    justifyContent: 'space-around',
    flexDirection:'row',
    borderBlockColor: '#128912',
    borderTopWidth: 2,
  },
  chgDisplayBtns: {
    position: "absolute",
    top: 0,
    width: '100%',
    height: '11%',
    alignItems: 'center',
    justifyContent: 'space-around',
    flexDirection: 'row',
  },
  inputsContainer: {
    position: "absolute",
    top: 50,
    width: '100%',
    height: '11%',
    alignItems: 'center',
    justifyContent: 'space-around',
    flexDirection: 'row',
    zIndex: 5,
  },
  listRecords: {
    position: 'absolute',
    width:'100%',
    top: 115,
    height: '79%',
    alignItems: 'center',
    justifyContent: 'start',
    flexDirection: 'column',
  },
  record: {
    backgroundColor: '#56789a',
    width:'95%',
    marginBottom: 3,
    borderRadius: 10,
    padding: 10,
    alignItems: 'center',
    justifyContent: 'space-around',
    flexDirection: 'row',
    elevation: 5
  },
  stats: {
    textAlign:'center',
    backgroundColor: '#123456',
    borderRadius: 10,
    padding: 10,
    elevation: 10,
  
  },
  chgDisplayBtn: {
    marginTop:5,
    backgroundColor: '#125624',
    borderRadius: 10,
    padding: 11,
    color: '#e9e9e9',
    fontSize: 14,
    fontWeight: 'bold'
  },
  saveBtn: {
    position: 'absolute',
    bottom: 5,
    right: '43%',
    backgroundColor: '#aa3477',
    borderRadius: 20,
    padding: 13,
    elevation: 5,
  },
  editBtn: {
    width: '78%',
    textAlign: 'center',
    backgroundColor: '#e9ffe9',
    borderRadius: 5,
    padding: 5,
    marginBottom: '5%',
    elevation: 5,
  },
  ctrlBtn: {
    textAlign: 'center',
    backgroundColor: '#e9ffe9',
    borderRadius: 5,
    padding: 10,
    margin: 5,
    elevation: 5,
  },
  bcBtn: {
    textAlign: 'center',
    backgroundColor: '#e9ffe9',
    borderRadius: 5,
    padding: 5,
    elevation:3,
  },
  deleteBtn: {
    textAlign: 'center',
    width: '78%',
    backgroundColor: '#ffaaaa',
    borderRadius: 5,
    padding: 5,
    elevation: 5,
  },
  logo: {
    position: "absolute",
    fontSize: 34,
    fontWeight: 'bold',
    color: '#128912',
    textShadowColor: 'rgba(0, 0, 0, 0.75)',
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 5,
  },
  date: {
    position: 'absolute',
    top: '21%',
    right: '3%',
    fontSize: 12,
    fontWeight: 'bold',
    color: '#128912',
  },
  table: {

    width: "100%",
    flex: 1,
    flexDirection: 'column',
    borderWidth: 2,
    borderColor: 'black',
  },
  table2: {
    flex:1,
    alignItems: 'center',
    justifyContent: 'center',
    width: "89%",
    flex: 1,
    flexDirection: 'column',
  },
  row: {
    flexDirection: 'row',
  },
  cell: {
    flex: 1,
    padding: 8,
    borderWidth: 1,
    borderColor: 'black',
    fontSize: 10,
  },
  cell2: {
    textAlign:'center',
    flex: 1,
    padding: 8,
    fontSize: 12,
  },
  formProduct: {
    position: 'absolute',
    backgroundColor:'#d9d9d9',
    elevation:20,
    zIndex: 5,
    top: '0%',
    right:'',
    width: '100%',
    height: '75%',
    alignItems: 'center',
    justifyContent: 'space-around',
    flexDirection:'column',
    borderRadius:10
  },
  productInput: {
    textAlign: 'center',
    borderBottomWidth: 1
  } ,
  check: {
    textAlign:'center',
    backgroundColor:'#d9d9d9',
    width: 340,
    minHeight: 168,
    alignItems: 'center',
    flexDirection:'column',
    borderBlockColor: 'black',
    borderWidth: 1,
    borderRadius:10,
    marginRight: 10,
    marginBottom: 60,
    padding:5,
  },
});
  
export default styles